version: 1
theme:
  bg: '#000000'
pages:
- id: main
  title: Main
  style: {}
  widgets:
  - id: tb_relic_result
    x: 0.65
    y: 120
    w: clamp(500px, 50dvw, 1000px)
    h: 120
    z: 8
    style:
      font_size: 12
      radius: 4
      border_color: '#242424'
      border_w: 0
      padding: 0
    conditions:
      rules:
      - effect: show
        source: activity:live
        op: ==
        value: '1'
      - effect: match
        source: ''
        op: nonempty
        value: ''
      visible_when: '{{activity:live}} == 1'
      enabled_when: ''
    type: table
    config:
      columns:
      - key: slug
        enabled: false
      - key: _seq
        enabled: false
      - key: live_sellers
        enabled: false
      - key: live_median
        enabled: false
      - key: price_min
        enabled: false
      - key: live_ask
        enabled: false
      - key: volume
        enabled: false
      - key: price_median
        enabled: false
      - key: key
        enabled: false
      - key: updated
        enabled: false
      pageSize: 4
      sortDesc: true
      sortField: price
      paging: false
    binding:
      src: subset
      id: relic_rewards_price_from_stored
    anchor:
      to: ''
      corner: tc
      target: tc
    units:
      x: dvw
      w: calc
  - id: pn_sess
    x: 0
    y: 3
    w: 34.51
    h: 300
    z: 2
    style:
      border_color: '#242424'
      border_w: 1
      radius: 4
      padding: 6
    conditions:
      rules: []
    type: panel
    config:
      panel: precap
    anchor:
      to: pn_tasks
      corner: tr
      target: br
    units:
      w: dvw
      y: dvh
    matchW: tb_relic_result
  - id: pn_live
    x: 0
    y: 3.64
    w: 16.93
    h: 280
    z: 3
    style:
      border_w: 1
      border_color: '#242424'
      padding: 6
      radius: 4
    conditions:
      rules: []
    type: panel
    config:
      panel: live
    anchor:
      to: hd_l
      corner: tl
      target: bl
    units:
      w: dvw
      h: px
    matchW: hd_l
  - id: pn_tasks
    x: 0
    y: 4
    w: 16
    h: 220
    z: 4
    style:
      border_w: 1
      border_color: '#242424'
      radius: 4
      padding: 6
    conditions:
      rules: []
    type: panel
    config:
      panel: activity
    anchor:
      to: hd_r
      corner: tr
      target: br
    units:
      w: dvw
    matchW: pn_live
    matchH: pn_live
  - id: hd_r
    x: 0
    y: 3
    w: 16.28
    h: 20
    z: 5
    style:
      bg: rgb(0, 0, 0, 0)
    conditions:
      rules: []
    type: label
    config:
      text: Tasks
    anchor:
      to: tb_relic_result
      corner: tr
      target: br
    units:
      w: dvw
      y: dvh
    matchW: hd_l
  - id: hd_l
    x: 0
    y: 3
    w: 16
    h: 20
    z: 6
    style:
      bg: rgb(0, 0, 0, 0)
      font_size: 14
      bold: true
    conditions:
      rules: []
    type: label
    config:
      text: Live
    units:
      w: dvw
      y: dvh
    anchor:
      to: tb_relic_result
      corner: tl
      target: bl
    matchW: tb_relic_result
    matchWPct: 48
  - id: hd_main
    x: 0
    y: -4
    w: 240
    h: 20
    z: 7
    style: {}
    conditions:
      rules: []
      visible_when: ''
      enabled_when: ''
    type: label
    config:
      text: Relic results
    units:
      x: dvw
    anchor:
      to: tb_relic_result
      corner: bl
      target: tl
    matchW: tb_relic_result
  - id: w1
    x: 2204
    y: 135
    w: 240
    h: 44
    z: 8
    style: {}
    conditions:
      rules: []
    type: label
    config:
      text: Label
- id: page1
  title: Page
  style: {}
  widgets: []
