name: warframe
process_names:
- Warframe.x64.exe
window_title_hint: Warframe
fields:
- id: name
  type: text
  extract: whole
  separator: /
  if_number_any: false
  if_text_any: false
  dict_mode: correct
  learn: true
  fuzzy: 0.82
- id: count
  type: number
  extract: whole
  separator: /
  if_number_any: false
  if_text_any: false
  dict_mode: correct
  learn: false
  fuzzy: 0.82
- id: rank
  type: number
  extract: whole
  separator: /
  if_number_any: false
  if_text_any: false
  dict_mode: correct
  learn: false
  fuzzy: 0.82
windows:
- id: equip
  dataset: master
  fields:
  - id: name
    type: text
    extract: text_before
    separator: '['
    if_number_any: false
    if_text_any: false
    dict_mode: correct
    learn: false
    fuzzy: 0.82
  - id: count
    type: number
    extract: whole
    separator: /
    empty: '1'
    if_number_any: false
    if_text_any: true
    dict_mode: correct
    learn: false
    fuzzy: 0.82
  - id: arcane_level
    type: diamonds
    extract: whole
    separator: /
    if_number_any: false
    if_text_any: false
    dict_mode: correct
    learn: false
    fuzzy: 0.75
  data_area:
    x: 0.0392843423787693
    y: 0.17411803841927975
    w: 0.6493593537024408
    h: 0.6190721796808167
  detect:
  - id: detect_2
    enabled: true
    search:
      x: 0.09868772375184379
      y: 0.04085933584041986
      w: 0.12602492874274893
      h: 0.04192976141839593
    text: inventory
    threshold: 0.3
    included: true
  - id: detect_4
    enabled: true
    search:
      x: 0.4447061041676425
      y: 0.13236166920519268
      w: 0.04299029987998991
      h: 0.036458379478999554
    text: NAME
    threshold: 0.5
    included: true
  - id: detect_1
    enabled: true
    search:
      x: 0.5778084179119407
      y: 0.13189642358055376
      w: 0.04834284612974901
      h: 0.03582122837035165
    text: search
    threshold: 0.5
    included: true
  states: []
  regions: []
  items:
  - id: normal
    enabled: true
    box:
      x: 0.2559312955630544
      y: 0.4915660013455143
      w: 0.1079847262492227
      h: 0.2045250942121843
    cutout: item-20260609-195853-149790.png
    cutout_box:
      x: 0.21821501387762782
      y: 0.42295973658521346
      w: 0.17833698482487298
      h: 0.3201018038741048
    align: bottom
    priority: 0
    fields:
    - id: name
      box:
        x: 0.0008647839276872834
        y: 0.49963703467726983
        w: 0.9116685321352634
        h: 0.3566060056546523
      field: name
      tell: true
      tell_conf: 0.3
      align: ''
      enabled: true
    - id: count
      box:
        x: 0.0
        y: 0.0007938414839423913
        w: 0.6963926439460314
        h: 0.15434670589268576
      field: count
      tell: false
      tell_conf: 0.0
      align: ''
      enabled: true
    tells: []
    key:
      fields:
      - name
      sep: '|'
      case_sensitive: false
  - id: arcane
    enabled: true
    box:
      x: 0.47210222904238824
      y: 0.4936875861083346
      w: 0.10819738326573768
      h: 0.20548627306849146
    cutout: item-20260609-224909-757925.png
    cutout_box:
      x: 0.45085229291538953
      y: 0.4333247423805847
      w: 0.1498718975200488
      h: 0.30097729443750454
    align: bottom
    priority: 5
    fields:
    - id: name
      box:
        x: 0.00011645597995694553
        y: 0.4921122085929414
        w: 0.9116495404421442
        h: 0.24518600148344633
      field: name
      tell: false
      tell_conf: 0.3
      align: none
      enabled: true
    - id: arcane_level
      box:
        x: 0.0
        y: 0.7379145017444578
        w: 0.9123235573101921
        h: 0.11592432005792572
      field: arcane_level
      tell: true
      tell_conf: 0.3
      align: ''
      enabled: true
    - id: count
      box:
        x: 0.0
        y: 0.0011458270119331794
        w: 0.3500557297941114
        h: 0.1548895564172534
      field: count
      tell: false
      tell_conf: 0.0
      align: ''
      enabled: true
    tells: []
    key:
      fields:
      - name
      - arcane_level
      sep: '|'
      case_sensitive: false
  scroll:
    enabled: true
    scrollbar:
      x: 0.6947506562840204
      y: 0.18695410233711787
      w: 0.00921298146337702
      h: 0.7211669337141035
    scrollbar_orientation: vertical
    rows: 8
    cols: 8
    row_stride: 0.205
    col_stride: 0.108
  preprocess:
    mode: none
    colors: []
    tolerance: 60
    scale: 1.0
datasets:
- id: master
  aggregate: latest
- id: prices
  aggregate: latest
subsets:
- id: master_view
  dataset: ''
  datasets:
  - master
  - prices
  join_field: name
  filters:
  - field: slug
    op: nonempty
    value: ''
  derived: []
  enrich:
  - id: enr_1
    type: warframe_market
    source_field: name
    enabled: true
  sort_by: ''
  sort_desc: false
  limit: 0
price_nodes:
- id: price
  type: warframe_market
  dataset: prices
  throttle: 0.4
  enabled: true
dictionaries:
- id: wiki
  name: wiki
  enabled: true
  source: wiki.txt
layout:
  nodes:
    game:
      x: -820.0
      y: -500.0
      collapsed: false
    fld:equipment:field_1:
      x: 680.0
      y: 340.0
      collapsed: false
    ds:equipment:
      x: 1100.0
      y: 100.0
      collapsed: false
    reg:equipment:item_name:
      x: 0.0
      y: 680.0
      collapsed: false
    reg:equipment:field_1:
      x: 420.0
      y: 880.0
      collapsed: false
    reg:equipment:field_2:
      x: 60.0
      y: 1020.0
      collapsed: false
    reg:equipment:field_3:
      x: 1020.0
      y: 0.0
      collapsed: false
    reg:equipment1:item_name:
      x: 680.0
      y: 0.0
      collapsed: false
    reg:equipment1:field_1:
      x: 600.0
      y: 120.0
      collapsed: false
    ds:equipment1:
      x: 1120.0
      y: 0.0
      collapsed: false
    anc:equipment:title:
      x: 640.0
      y: 240.0
      collapsed: false
    anc:equipment1:title:
      x: 600.0
      y: 220.0
      collapsed: false
    anc:equipment:anchor_1:
      x: 0.0
      y: 320.0
      collapsed: false
    anc:equipment:anchor_2:
      x: 0.0
      y: 400.0
      collapsed: false
    st:equipment:order_by_name:
      x: 600.0
      y: 140.0
      collapsed: false
    st:equipment:search:
      x: 920.0
      y: 320.0
      collapsed: false
    reg:equipment:count:
      x: 80.0
      y: 1020.0
      collapsed: false
    reg:equipment:item_count:
      x: 0.0
      y: 1000.0
      collapsed: false
    sb:equipment:scrollbar:
      x: 1040.0
      y: 660.0
      collapsed: false
    img:equipment:
      x: 320.0
      y: 440.0
      collapsed: false
    anc:equipment:detect_1:
      x: 600.0
      y: 240.0
      collapsed: false
    anc:equipment:detect_3:
      x: 600.0
      y: 548.0
      collapsed: false
    anc:equipment:detect_4:
      x: 600.0
      y: 718.0
      collapsed: false
    prev:equipment:
      x: 960.0
      y: 300.0
      collapsed: false
    anc:equipment:search:
      x: 280.0
      y: 240.0
      collapsed: false
    img:equip:
      x: 320.0
      y: 380.0
      collapsed: false
    win:equip:
      x: 380.0
      y: 180.0
      collapsed: false
    anc:equip:detect_2:
      x: 1220.0
      y: 440.0
      collapsed: false
    sb:equip:scrollbar:
      x: 1080.0
      y: 20.0
      collapsed: false
    prev:equip:
      x: 320.0
      y: 740.0
      w: 360.0
      h: 320.0
      collapsed: false
    anc:equip:detect_4:
      x: 1220.0
      y: 620.0
      collapsed: false
    anc:equip:detect_1:
      x: 1220.0
      y: 140.0
      collapsed: false
    reg:equip:item_name:
      x: 40.0
      y: 880.0
      collapsed: false
    reg:equip:item_count:
      x: 40.0
      y: 580.0
      collapsed: false
    item:equip:item_3:
      x: -480.0
      y: 220.0
      collapsed: false
    item:equip:item_2:
      x: -60.0
      y: 220.0
      collapsed: false
    item:equip:arcane:
      x: -120.0
      y: 260.0
      w: 380.0
      h: 1374.0
      collapsed: false
    item:equip:item:
      x: -560.0
      y: 240.0
      w: 380.0
      h: 1132.0
      collapsed: false
    dsp:equip:
      x: 920.0
      y: -780.0
      collapsed: false
    ds:equip-copy:
      x: 900.0
      y: 20.0
      collapsed: false
    dict:wiki:
      x: -420.0
      y: -500.0
      w: 320.0
      h: 280.0
      collapsed: false
    sub:equip_view:
      x: 800.0
      y: -1680.0
      w: 0.0
      h: 0.0
      collapsed: false
    sub:equip_view2:
      x: 1840.0
      y: -1040.0
      w: 0.0
      h: 0.0
      collapsed: false
    item:equip:normal:
      x: -540.0
      y: 240.0
      collapsed: false
    det:equip:detect_2:
      x: 1080.0
      y: 220.0
      collapsed: false
    det:equip:detect_4:
      x: 1080.0
      y: 400.0
      collapsed: false
    det:equip:detect_1:
      x: 1080.0
      y: 580.0
      collapsed: false
    bat:master:
      x: 1040.0
      y: -1100.0
      w: 840.0
      h: 380.0
      collapsed: false
    item:equip:normal1:
      x: 300.0
      y: 20.0
      collapsed: false
    ds:master:
      x: 120.0
      y: -760.0
      w: 880.0
      h: 780.0
      collapsed: false
    bat:equip:
      x: 1180.0
      y: 20.0
      w: 0.0
      h: 0.0
      collapsed: false
    ds:equip:
      x: 900.0
      y: 178.0
      w: 0.0
      h: 0.0
      collapsed: false
    sub:master_view:
      x: 1940.0
      y: -620.0
      w: 1080.0
      h: 720.0
      collapsed: false
    bat:prices:
      x: 2020.0
      y: 1060.0
      w: 780.0
      h: 420.0
      collapsed: false
    enr:master_view:enr_1:
      x: 2460.0
      y: -200.0
      w: 860.0
      h: 760.0
      collapsed: false
    ds:prices:
      x: 1800.0
      y: 200.0
      w: 1240.0
      h: 800.0
      collapsed: false
    price:price:
      x: 1020.0
      y: 1060.0
      w: 920.0
      h: 880.0
      collapsed: false
    enr:master_view:enr_2:
      x: 0.0
      y: 0.0
      w: 0.0
      h: 0.0
      collapsed: false
  tables:
    warframe:ds:master:
      sorts:
      - col: key
        dir: 1
      widths:
        key: 190
    warframe:view:master_view:
      sorts:
      - col: count
        dir: 1
      widths:
        _item: 92
        count: 226
        key: 249
        volume: 41
  open_images:
  - equip
  groups:
  - id: group_1
    title: group_1
    members:
    - det:equip:detect_2
    - det:equip:detect_4
    - det:equip:detect_1
    outline:
      color: '#5aa9e6'
      style: solid
      width: 2
    bg: '#5aa9e612'
    titlePos: tl
