version: 1
theme:
  bg: '#000000'
pages:
- id: main
  title: Main
  style: {}
  widgets:
  - id: w3
    x: 32.5
    y: 50
    w: 35
    h: 140
    z: 8
    style:
      font_size: 12
    conditions:
      rules:
      - effect: show
        source: ''
        op: nonempty
        value: ''
      - effect: show
        source: ''
        op: nonempty
        value: ''
      visible_when: ''
      enabled_when: ''
    type: table
    config:
      columns:
      - key: name
        enabled: true
      - key: live_ask
        enabled: true
      - key: live_median
        enabled: true
      - key: live_sellers
        enabled: true
      - key: price_median
        enabled: false
      - key: price_min
        enabled: false
      - key: updated
        enabled: false
      - key: volume
        enabled: false
      - key: slug
        enabled: false
      - key: key
        enabled: false
      - key: _seq
        enabled: false
      pageSize: 4
      sortDesc: true
      sortField: ''
      paging: false
    binding:
      src: subset
      id: relic_rewards_live
    anchor:
      to: ''
      corner: tl
    units:
      x: dvw
      w: dvw
  - id: w1
    x: 0
    y: 420
    w: 35
    h: 300
    z: 2
    style: {}
    conditions:
      rules: []
    type: panel
    config:
      panel: precap
    anchor:
      to: w2
      corner: bl
    units:
      w: dvw
  - id: w2
    x: 0
    y: 200
    w: 16
    h: 220
    z: 3
    style: {}
    conditions:
      rules: []
    type: panel
    config:
      panel: live
    anchor:
      to: w3
      corner: tl
    units:
      w: dvw
  - id: w4
    x: 0
    y: 230
    w: 16
    h: 220
    z: 4
    style: {}
    conditions:
      rules: []
    type: panel
    config:
      panel: activity
    anchor:
      to: w5
      corner: br
    units:
      w: dvw
  - id: w5
    x: 0
    y: 50
    w: 16
    h: 20
    z: 5
    style:
      bg: rgb(0, 0, 0, 0)
    conditions:
      rules: []
    type: label
    config:
      text: Tasks
    anchor:
      to: w3
      corner: br
    units:
      w: dvw
  - id: w6
    x: -0.4
    y: 50
    w: 16
    h: 20
    z: 6
    style:
      bg: rgb(0, 0, 0, 0)
    conditions:
      rules: []
    type: label
    config:
      text: Label
    units:
      w: dvw
    anchor:
      to: w3
      corner: bl
