version: 1
theme:
  bg: '#000000'
  border_w: 0
pages:
- id: main
  title: Main
  style: {}
  widgets:
  - id: tb_relic_result
    x: 0
    y: 4
    w: 986
    h: 120
    z: 8
    style:
      font_size: 12
      radius: 4
      border_color: '#242424'
      border_w: 0
      padding: 0
      opacity: 1
    conditions:
      rules:
      - effect: show
        source: activity:live
        op: ==
        value: '1'
      visible_when: '{{activity:live}} == 1'
      enabled_when: ''
    type: table
    config:
      columns:
      - key: slug
        enabled: false
      - key: _seq
        enabled: false
      - key: live_sellers
        enabled: false
      - key: live_median
        enabled: false
      - key: price_min
        enabled: false
      - key: live_ask
        enabled: false
      - key: volume
        enabled: false
      - key: price_median
        enabled: false
      - key: key
        enabled: false
      - key: updated
        enabled: false
      pageSize: 4
      sortDesc: true
      sortField: price
      paging: false
    binding:
      src: subset
      id: relic_rewards_with_price
    anchor:
      to: hd_main
      corner: tc
      target: bc
    units:
      x: px
      w: px
      y: px
    matchW: hd_main
    styleProfiles: []
    configProfiles: []
  - id: pn_sess
    x: 0
    y: 4
    w: 34.51
    h: 300
    z: 2
    style:
      border_color: '#242424'
      border_w: 1
      radius: 4
      padding: 6
    conditions:
      rules:
      - effect: show
        source: activity:live
        op: ==
        value: '0'
        state: both
      visible_when: '{{activity:live}} == 0'
      enabled_when: ''
    type: panel
    config:
      panel: precap
    anchor:
      to: hd_prec
      corner: tl
      target: bl
    units:
      w: dvw
      y: px
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: pn_live
    x: 0
    y: 4
    w: 16.93
    h: 280
    z: 3
    style:
      border_w: 1
      border_color: '#242424'
      padding: 6
      radius: 4
    conditions:
      rules: []
    type: panel
    config:
      panel: live
    anchor:
      to: hd_l
      corner: tl
      target: bl
    units:
      w: dvw
      h: px
      y: px
    matchW: hd_l
    styleProfiles: []
    configProfiles: []
  - id: pn_tasks
    x: 0
    y: 4
    w: 16
    h: 220
    z: 4
    style:
      border_w: 1
      border_color: '#242424'
      radius: 4
      padding: 6
    conditions:
      rules: []
    type: panel
    config:
      panel: activity
    anchor:
      to: hd_r
      corner: tr
      target: br
    units:
      w: dvw
      x: px
      y: px
    matchW: pn_live
    matchH: pn_live
    styleProfiles: []
    configProfiles: []
  - id: hd_r
    x: 0
    y: 64
    w: 16.28
    h: 20
    z: 5
    style:
      bg: rgb(0, 0, 0, 0)
    conditions:
      rules: []
    type: label
    config:
      text: Tasks
    anchor:
      to: game_name
      corner: tr
      target: br
    units:
      w: dvw
      y: px
      x: px
    matchW: hd_l
    styleProfiles: []
    configProfiles: []
  - id: hd_l
    x: 0
    y: 65
    w: 16
    h: 20
    z: 6
    style:
      bg: rgb(0, 0, 0, 0)
      font_size: 14
      bold: true
    conditions:
      rules: []
    type: label
    config:
      text: Live
    units:
      w: dvw
      y: px
    anchor:
      to: game_name
      corner: tl
      target: bl
    matchWPct: 48
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: hd_main
    x: 0
    y: 30
    w: 240
    h: 20
    z: 7
    style: {}
    conditions:
      rules:
      - effect: match
        source: tb_relic_result
        op: nonempty
        value: ''
        state: show
      visible_when: ''
      enabled_when: ''
    type: label
    config:
      text: Relic results
    units:
      x: px
      y: px
    anchor:
      to: pn_live
      corner: tl
      target: bl
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: game_name
    x: 50
    y: 100
    w: clamp(500px, 50dvw, 1000px)
    h: 50
    z: 8
    style:
      font_size: 36
      border_w: 1
      border_style: solid
      border_w_top: 0
      border_w_right: 0
      border_w_left: 0
      align: left
    conditions:
      rules: []
    type: label
    config:
      text: WARFRAME
    units:
      w: calc
      x: '%'
      h: px
    anchor:
      to: ''
      corner: tc
      target: tl
    onAllPages: true
    styleProfiles: []
    configProfiles: []
  - id: hd_prec
    x: 0
    y: 30
    w: 240
    h: 20
    z: 9
    style:
      border_w: 0
    conditions:
      rules:
      - effect: match
        source: pn_sess
        op: nonempty
        value: ''
        state: both
      visible_when: ''
      enabled_when: ''
    type: label
    config:
      text: Precapture
    matchW: game_name
    anchor:
      to: pn_live
      corner: tl
      target: bl
    styleProfiles: []
    configProfiles: []
  - id: btn_page_prime
    x: 10
    y: 0
    w: 100
    h: 40
    z: 10
    style:
      align: left
      padding: 0
      fill: true
      alignH: center
      bg: '#2c313c'
    conditions:
      rules:
      - effect: style
        source: page
        op: ==
        value: page1
        state: sp1
      visible_when: ''
      enabled_when: ''
    type: button
    config:
      action: switch_page
      target: ''
      value: ''
      page: page1
      label: Prime Parts
      alignH: center
      fill: true
    anchor:
      to: btn_page_main
      corner: tl
      target: tr
    onAllPages: true
    matchW: btn_page_main
    matchH: btn_page_main
    styleProfiles:
    - id: sp1
      name: active
      style:
        align: left
        padding: 0
        fill: true
        alignH: center
        bg: '#5aa9e6'
        color: '#000000'
    configProfiles: []
  - id: btn_page_live
    x: 10
    y: 0
    w: 100
    h: 40
    z: 10
    style:
      align: left
      padding: 0
      fill: true
      alignH: center
      bg: '#2c313c'
      opacity: 1
    conditions:
      rules:
      - effect: style
        source: page
        op: ==
        value: page2
        state: sp1
      visible_when: ''
      enabled_when: ''
    type: button
    config:
      action: switch_page
      target: ''
      value: ''
      page: page2
      label: Live
      alignH: center
      fill: true
    anchor:
      to: btn_page_prime
      corner: tl
      target: tr
    onAllPages: true
    matchW: btn_page_main
    matchH: btn_page_main
    styleProfiles:
    - id: sp1
      name: active
      style:
        align: left
        padding: 0
        fill: true
        alignH: center
        bg: '#5aa9e6'
        opacity: 1
        color: '#000000'
    configProfiles: []
  - id: w8
    x: 295
    y: 1049
    w: 240
    h: 44
    z: 20
    style: {}
    conditions:
      rules: []
    type: label
    config:
      text: '{{dataset:master.name[0:5]}}'
    styleProfiles: []
    configProfiles: []
- id: page1
  title: Prime Parts
  style: {}
  widgets:
  - id: btn_page_main
    x: 0
    y: 9
    w: 100
    h: 28
    z: 11
    style:
      fill: true
      bg: '#2c313c'
    conditions:
      rules:
      - effect: style
        source: page
        op: ==
        value: main
        state: sp1
      visible_when: ''
      enabled_when: ''
    type: button
    config:
      action: switch_page
      target: ''
      value: ''
      page: main
      label: Main
      alignH: left
      alignV: middle
      fill: true
    anchor:
      to: game_name
      corner: tl
      target: bl
    onAllPages: true
    styleProfiles:
    - id: sp1
      name: active
      style:
        fill: true
        bg: '#5aa9e6'
        color: '#000000'
    configProfiles: []
  - id: w2
    x: 0
    y: 4
    w: 1000
    h: 1140
    z: 12
    style: {}
    conditions:
      rules: []
    type: table
    config:
      columns:
      - key: arcane_level
        enabled: false
      - key: _seq
        enabled: false
      - key: key
        enabled: false
      - key: price_median
        enabled: false
      - key: volume
        enabled: false
      - key: live_ask
        enabled: false
      - key: live_median
        enabled: false
      - key: live_sellers
        enabled: false
      - key: slug
        enabled: false
      - key: name
        enabled: true
        width: 35
      - key: count
        enabled: true
        width: 10
      - key: price_min
        enabled: true
        width: 10
      - key: updated
        enabled: true
        width: 20
      pageSize: 20
      paging: true
      sortField: price_min
      sortDesc: true
    binding:
      src: subset
      id: master_prime_parts
    anchor:
      to: w3
      corner: tl
      target: bl
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: w3
    x: 0
    y: 65
    w: 240
    h: 20
    z: 13
    style: {}
    conditions:
      rules: []
    type: label
    config:
      text: 'Prime parts (total: {{subset:master_prime_parts}})'
    anchor:
      to: game_name
      corner: tl
      target: bl
    styleProfiles: []
    configProfiles: []
- id: page2
  title: Live
  style: {}
  widgets:
  - id: w1
    x: 0
    y: 65
    w: 240
    h: 20
    z: 13
    style: {}
    conditions:
      rules: []
    type: label
    config:
      text: Relic results
    anchor:
      to: game_name
      corner: tl
      target: bl
    styleProfiles: []
    configProfiles: []
  - id: w4
    x: 0
    y: 4
    w: 780
    h: 120
    z: 8
    style:
      font_size: 12
      radius: 4
      border_color: '#242424'
      border_w: 0
      padding: 0
      opacity: 1
    conditions:
      rules:
      - effect: enable
        source: activity:live
        op: '!='
        value: '1'
      visible_when: ''
      enabled_when: '{{activity:live}} != 1'
    type: table
    config:
      columns:
      - key: _seq
        enabled: false
      - key: updated
        enabled: false
      - key: key
        enabled: false
      - key: price
        enabled: false
      - key: live_sellers
        enabled: false
      - key: live_median
        enabled: false
      - key: live_ask
        enabled: false
      - key: volume
        enabled: false
      - key: price_median
        enabled: false
      - key: slug
        enabled: false
      sortField: price_min
      sortDesc: true
    binding:
      src: subset
      id: relic_rewards_with_price
    anchor:
      to: w1
      corner: tl
      target: bl
    units:
      x: px
      w: px
      y: px
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: w5
    x: 0
    y: 235
    w: 240
    h: 20
    z: 13
    style: {}
    conditions:
      rules: []
    type: label
    config:
      text: Best relic select
    anchor:
      to: game_name
      corner: tl
      target: bl
    styleProfiles: []
    configProfiles: []
  - id: w6
    x: 0
    y: 4
    w: 780
    h: 240
    z: 8
    style:
      font_size: 12
      radius: 4
      border_color: '#242424'
      border_w: 0
      padding: 0
      opacity: 1
    conditions:
      rules: []
      visible_when: ''
      enabled_when: ''
    type: table
    config:
      columns:
      - key: key
        enabled: false
      - key: updated
        enabled: false
      - key: _seq
        enabled: false
      - key: rarity
        enabled: false
      - key: price_median
        enabled: false
      - key: volume
        enabled: false
      - key: live_sellers
        enabled: false
      - key: live_median
        enabled: false
      - key: live_ask
        enabled: false
      - key: slug
        enabled: false
      - key: state
        enabled: false
      - key: chance
        enabled: false
      pageSize: 10
      sortDesc: true
      sortField: price_min
      paging: false
    binding:
      src: subset
      id: contents_with_price
    anchor:
      to: w5
      corner: tl
      target: bl
    units:
      x: px
      w: px
      y: px
    matchW: game_name
    styleProfiles: []
    configProfiles: []
  - id: w7
    x: 0
    y: 9
    w: 120
    h: 28
    z: 19
    style:
      alignH: center
      alignV: middle
      fill: true
      bg: var(--danger)
      radius: 4
      color: '#000000'
    conditions:
      rules:
      - effect: style
        source: activity:live
        op: ==
        value: '1'
        state: sp1
      - effect: config
        source: activity:live
        op: ==
        value: '1'
        state: sp1
      visible_when: ''
      enabled_when: ''
    type: button
    config:
      action: live_toggle
      target: ''
      value: ''
      page: ''
      label: 'live: disabled'
    styleProfiles:
    - id: sp1
      name: live_on
      style:
        alignH: center
        alignV: middle
        fill: true
        bg: var(--ok)
        border_w: 0
        radius: 4
        color: '#000000'
    anchor:
      to: game_name
      corner: tr
      target: br
    configProfiles:
    - id: sp1
      name: live_on
      config:
        action: live_toggle
        target: ''
        value: ''
        page: ''
        label: 'live: enabled'
